export const environment = {
  production: true,

  BASE_API_SERVER: "https://localhost:44355/",
  BASE_API_PATH: "https://localhost:44355/api/sahosoft/",
  BASE_IMAGES_PATH: "https://localhost:44355/images/",
  BASE_USERS_IMAGES_PATH: "https://localhost:44355/images/users/",
  BASE_COURSES_PATH: "https://localhost:44355/courses/",
  BASE_FACULTY_PATH: "https://localhost:44355/faculty/",
  BASE_BOOKS_PATH: "https://localhost:44355/books/",
  BASE_TESTIMONIAL_PATH: "https://localhost:44355/testimonial/",
  BASE_VIDEOS_PATH: "https://localhost:44355/videos/",
  BASE_GENERAL_PATH: "https://localhost:44355/general/",
  BASE_RESUME_PATH:"https://localhost:44355/resume/",
  BASE_API_PATH_MYCLASS: "https://localhost:44355/api/myclass/",
  BASE_API_PATH_EXAM: "https://localhost:44355/api/exam/",
  BASE_EXAM_PATH:"https://localhost:44355/exam/",
  BASE_API_PATH_VIDEO_PASSWORD: "https://localhost:44355/videopassword/",
  BASE_ASSIGNMENT_SOLUTION_PATH: "https://localhost:44355/AssignmentAttachments/",
  BASE_ASSIGNMENT_ZIP_PATH: "https://localhost:44355/AssignmentFiles/",
  BASE_API_PATH_PASSWORDREISSUE: "https://localhost:44355/PasswordReNew/",
  BASE_API_PATH_DOUBTATTACHMENTPATH: "https://localhost:44355/MyClassDoubt/",
  BASE_API_PATH_PROJECTDOUBTATTACHMENTPATH: "https://localhost:44355/MyProjectDoubt/",
  BASE_BLOG_IMAGE_PATH: "https://localhost:44355/Blog/",
  BASE_AUTHOR_PATH: "https://localhost:44355/BlogAuthor/",
  BASE_BLOG_COURSE_PATH: "https://localhost:44355/BlogCourses/",
  BASE_LEAVE_URL_FOR_USER: "https://localhost:4200/user-panel/my-class/my-live-class",
  BASE_LEAVE_URL_FOR_FACULTY: "https://localhost:4200/faculty/faculty-courses/faculty-live-class",
  BASE_SYSTEMCONFIG_IMAGE: "https://localhost:44355/SystemConfigImage/",

  // BASE_STREAMVIDEO_PATH:'http://localhost:3001/stream/',



  // BASE_API_SERVER: "https://sahosofttech.live/",
  // BASE_API_PATH: "https://sahosofttech.live/api/sahosoft/",
  // BASE_IMAGES_PATH: "https://sahosofttech.live/images/",
  // BASE_USERS_IMAGES_PATH: "https://sahosofttech.live/images/users/",
  // BASE_COURSES_PATH: "https://sahosofttech.live/courses/",
  // BASE_FACULTY_PATH: "https://sahosofttech.live/faculty/",
  // BASE_BOOKS_PATH: "https://sahosofttech.live/books/",
  // BASE_TESTIMONIAL_PATH: "https://sahosofttech.live/testimonial/",
  // BASE_VIDEOS_PATH: "https://sahosofttech.live/videos/",
  // BASE_GENERAL_PATH: "https://sahosofttech.live/general/",
  // BASE_RESUME_PATH: "https://sahosofttech.live/resume/",
  // BASE_API_PATH_MYCLASS: "https://sahosofttech.live/api/myclass/",
  // BASE_API_PATH_EXAM: "https://sahosofttech.live/api/exam/",
  // BASE_EXAM_PATH: "https://sahosofttech.live/exam/",
  // BASE_API_PATH_VIDEO_PASSWORD: "https://sahosofttech.live/videopassword/",
  // BASE_ASSIGNMENT_SOLUTION_PATH: "https://sahosofttech.live/AssignmentAttachments/",
  // BASE_ASSIGNMENT_ZIP_PATH: "https://sahosofttech.live/AssignmentFiles/",
  // BASE_API_PATH_PASSWORDREISSUE: "https://sahosofttech.live/PasswordReNew/",
  // BASE_API_PATH_DOUBTATTACHMENTPATH: "http://sahosofttech.live/MyClassDoubt/",
  // BASE_API_PATH_PROJECTDOUBTATTACHMENTPATH: "http://sahosofttech.live/MyProjectDoubt/",
  // BASE_BLOG_IMAGE_PATH: "http://sahosofttech.live/Blog/",
  // BASE_AUTHOR_PATH: "http://sahosofttech.live/BlogAuthor/",
  // BASE_BLOG_COURSE_PATH: "http://sahosofttech.live/BlogCourses/",
  // BASE_LEAVE_URL_FOR_USER: "https://www.sahosofttech.com/user-panel/my-class/my-live-class",
  // BASE_LEAVE_URL_FOR_FACULTY: "https://www.sahosofttech.com/faculty/faculty-courses/faculty-live-class",
  // BASE_SYSTEMCONFIG_IMAGE: "http://sahosofttech.live/SystemConfigImage/",

  BASE_STREAMVIDEO_PATH: 'https://play-online-video-streaming.onrender.com/stream/',
  BASE_VIDEO_API_PATH: "https://play-online-video-api.onrender.com/api/",




};
